/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iperfer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Iperfer classUnderTest = new Iperfer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
