/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iperfer;

import org.apache.commons.cli.*;

import java.io.*;
import java.net.Socket;
import java.time.Duration;
import java.time.Instant;
import java.util.Timer;


public class Iperfer {
    public String getGreeting() {
        return "Hello world.";
    }

    private static void runServer(String portNum) {
        int port = Integer.parseInt(portNum);
        if (port < 1024 || port > 65535) {
            System.err.println("Error: port number must be in the range 1024 to 65535.");
            printHelpAndExit();
        }
        try {
            Socket serverSocket = new Socket("127.0.0.1", port);
            InputStream inputStream = serverSocket.getInputStream();
            byte[] bytes = new byte[1024];
            int len;
            StringBuilder sb = new StringBuilder();
            Instant start = Instant.now();
            while ((len = inputStream.read(bytes)) != -1) {
                sb.append(new String(bytes, 0, len, "UTF-8"));
            }
            Instant end = Instant.now();
            double timeTaken = Duration.between(start, end).toMillis() / 1000.0;
            double rate = len / timeTaken;
            System.out.println(String.format("received=%d KB rate=%f Mbps", len, rate));

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private static void runClient(String hostname, String portNum, String time) {
        try {
            Socket clientSocket = new Socket(hostname, Integer.parseInt(portNum));
            int timeToSend = Integer.parseInt(time);
            Timer timer = new Timer();

            OutputStream outToServer = clientSocket.getOutputStream();
            DataOutputStream out = new DataOutputStream(outToServer);
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    private static Options getOption() {
        Options options = new Options();
        Option serverOption = new Option("s", "server", false, "launch server");
        serverOption.setRequired(false);
        Option clientOption = new Option("c", "client", false, "launch client");
        clientOption.setRequired(false);
        Option portOption = new Option("p", "port", true, "port");
        portOption.setRequired(true);
        Option hostOption = new Option("h", "hostname", true, "hostname of server");
        hostOption.setRequired(false);
        Option timeOption = new Option("t", "time", true, "time of client");
        timeOption.setRequired(false);
        options.addOption(serverOption);
        options.addOption(clientOption);
        options.addOption(portOption);
        options.addOption(hostOption);
        options.addOption(timeOption);
        return options;
    }

    private static Options options = getOption();
    static HelpFormatter formatter = new HelpFormatter();

    private static void printHelpAndExit() {
        formatter.printHelp("Iperfer", options);
        System.exit(-1);
    }

    public static void main(String[] args) {

        CommandLineParser parser = new DefaultParser();

        CommandLine cmd = null;
        try {
            cmd = parser.parse(options, args);
        } catch (ParseException e) {
            printHelpAndExit();
        }

        assert cmd != null;
        if (!cmd.hasOption("port")) {
            System.err.println("Error: missing or additional arguments");
            printHelpAndExit();
        }
        String portNum = cmd.getOptionValue("port");

        if (cmd.hasOption("client")) {
            if (!cmd.hasOption("time") || !cmd.hasOption("hostname")) {
                System.err.println("Error: missing or additional arguments");
                printHelpAndExit();
            }
            String time = cmd.getOptionValue("time");
            String host = cmd.getOptionValue("hostname");
            if (time == null || host == null || portNum == null) printHelpAndExit();
            runClient(host, portNum, time);
        } else if (cmd.hasOption("server")) {
            if (portNum == null) printHelpAndExit();
            runServer(portNum);
        } else printHelpAndExit();

        System.out.println(new Iperfer().getGreeting());
    }
}
